bot:
  abi_migration_branches:
  - v7.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux: github_actions
  linux_aarch64: github_actions
  linux_ppc64le: github_actions
  osx: github_actions
  win: github_actions
github_actions:
  artifact_retention_days: 14
  free_disk_space: true
  self_hosted: false
test: native_and_emulated
